gui:
  scrollHeight: 4 # how many lines you scroll by
  theme:
    selectedLineBgColor:
      # - '#414858'
      - '#f2e9e1'
    selectedRangeBgColor:
      # - '#414858'
      - '#dfdad9'
keybinding:
  universal:
    prevPage: '<c-b>' # go to next page in list
    nextPage: '<c-f>' # go to previous page in list
    # prevBlock-alt: 'h' # goto the previous block / panel
    # nextBlock-alt: 'l' # goto the next block / panel
    prevBlock-alt: '<c-k>' # goto the previous block / panel
    nextBlock-alt: '<c-j>' # goto the next block / panel
    scrollLeft: 'h' # scroll left within list view
    scrollRight: 'l' # scroll right within list view
    scrollUpMain-alt1: null # main panel scroll up
    scrollDownMain-alt1: null # main panel scroll down
  commits:
    moveDownCommit: 'J' # move commit down one
    moveUpCommit: 'K' # move commit up one

