add_newline = false

[line_break]
disabled = true

[cmd_duration]
disabled = true

[package]
disabled = true

[conda]
ignore_base = false
symbol = " "

[python]
disabled = true

[java]
disabled = true

[cmake]
disabled = true

[lua]
disabled = true

[c]
disabled = true

[git_branch]
symbol = " "

[hg_branch]
symbol = " "

[memory_usage]
symbol = " "

