format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$python\
$jobs\
$battery\
$character"""
add_newline = false

[line_break]
disabled = true

[cmd_duration]
disabled = true

[package]
disabled = true

[python]
disabled = false
format = '[(\($virtualenv\) )]($style)'

[git_branch]
symbol = " "

[hg_branch]
symbol = " "

[memory_usage]
symbol = " "

