require('configs.mason')
require('configs.lspconfig')
require('configs.nvim-treesitter')
require('configs.telescope')
require('configs.nvim-autopairs')
require('configs.nvim-tree')
require('configs.cmp')
-- require('configs.vim-sneak')
-- require('configs.lsp_signature')
require('configs.copilot')
require('configs.tagbar')
require('configs.luasnip')
require('configs.Comment')
require('configs.Navigator')
-- require('configs.eyeliner')
require('configs.toggleterm')

require('configs.themes')
require('configs.lualine')

